"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8&1u%oz5zbs8k-(m*6k6ecpqz_dprb#u_*-81tk6=c=la)bynt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'djcelery',
    'Seller',
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.middleware.MiddleWareTest',
    'django.middleware.cache.FetchFromCacheMiddleware'
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,"static"),
)
# STATIC_ROOT = os.path.join(BASE_DIR,"static") #静态文件的根目录，和STATICFILES_DIRS，MEDIA_URL，MEDIA_ROOT有冲突

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"static")



alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0/x9pVL5lA8qre5VuYMJpgNQX2XAdkuou/nAT5Rf5mAJocI73gVgTXhPOTyp4qXiUTyvGa0jo7HPMoHEmfIquvMJWeOnoj4wlhyqEvjTst2l6GdLg6/dPJBxT9wQSZxSpOsi+DH8G4Z7p9NPkCcSfIHTmgPdVuOCvgemvbl+9jgkf3blz1jvc5Zj+VGIVAigsCD8ryC2waPMIE9WQe54kKnIVmda7+cbxfMstSJKEZgD1e5LjNF6Xu7xBmXIq+XJrhKgFBq/EoK1No+F/Tr4j9/g3zhKVm07UsngDcQN2AnPViqyFgjAlfU4MpeKzxGgF6xJ/k0Hs+kzmuSyuUB24wIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA0/x9pVL5lA8qre5VuYMJpgNQX2XAdkuou/nAT5Rf5mAJocI73gVgTXhPOTyp4qXiUTyvGa0jo7HPMoHEmfIquvMJWeOnoj4wlhyqEvjTst2l6GdLg6/dPJBxT9wQSZxSpOsi+DH8G4Z7p9NPkCcSfIHTmgPdVuOCvgemvbl+9jgkf3blz1jvc5Zj+VGIVAigsCD8ryC2waPMIE9WQe54kKnIVmda7+cbxfMstSJKEZgD1e5LjNF6Xu7xBmXIq+XJrhKgFBq/EoK1No+F/Tr4j9/g3zhKVm07UsngDcQN2AnPViqyFgjAlfU4MpeKzxGgF6xJ/k0Hs+kzmuSyuUB24wIDAQABAoIBAGXHsuPvxNjrt0gvSIV7fuRwbuR+zDt/9BHcxhLvYGQR9E3wHiJpXmWTwCXxFHg3wUPT6RZg5N2xf5P2blijxxRfoDvCbDgft+A6/wWA5tPYS9Ib1kvx4j0z9NOtCzzsi1mXdADKrwrgNPrNIERMHjodc2VdOaaAMcPflJU/PNAmIBW7rGsFONcLFb4fkE8CbD8/uAaOmNLIGpkO95HDeXyHGW19S76PTJ+bXJQeNdewsHrggkJuqres7ZP7NrmYod78q35CCh1BHlAOic5KNeguPBTvQqGXcDuoTqhX3xKsOAvb83HOKoIZHinKWZ5eIHbfNCZ3f5k14eKZVTEYb5ECgYEA/TWDufqTMi+vnb3inBd1Ow+nYmU69HPf5NluydzZYvM+Skmrih8jhwHl4mF0GKcE0Ce9bm/98s+y4B9oH3vHL2hjWczoegUSy1lxaDOnsxT2E7soDPAO6Pt5PBNfotgHQUrP2WVbi3X5wosS3HBxHEYtFucioTbWJW68Jx89Ym8CgYEA1lKoOSsMCJFWmii13PghuuibY2cND05DGmBUULR2cW9mNFnnVP2EuxgcWzRmb5c0F+iQqUe148R6XAluZoypNTZ7j0fqhojtlQOwxdVCEypV5BcqW/Ns//+Kvl1/cyGh+juubDW3PpfCknrp8ZTcslBzNyUQerEp8MQTZN8znM0CgYA+4k94nLZ5vEYNEt94jIrcxCJ52VIu66grGaTeFS8X1/kcUfd8MgeMu/fvpOxEQxZ666OsDbwv1U1DRAmD6CWrrG0gHDeQNjpYrjnv+wQnAYmrlMt5ixTo36tYNCeINcZ3fLDp+LYniIEiw49Hl9U/hF4mVfjPuOKuITYxMRz5mQKBgQCb4HgrRAy3eoVDD9LdiLZ3i0/gpwWPmTsixubr36S5ce0irDSc0tojfTC6gMzz4kPoE6SLCfXXV4IqyE08VpeGdT6+ge6ntJUfKRT7fdRVvhfEEbkkMVKYihItzDCy2sZFCf0dBKBm7Nd909msc7lkEzEI7XMj2RCI5QK5/cA7DQKBgQCYtMvXk9dRvL0kGzz1Mdr/FUQugTEHuDC8KbC9YGPVh67jMG5AKuEaQxAoZME0PT9b+ifEdFavLoDz0bJrVMHmVL9ZW8l2peT6NAxcrcenHMGxG3ot/Q+SttLYrTaBSgP0+EHlPsDKXmgMYeBtop/rh7TOfPMcCvRemVZwOq+O8A==
-----END RSA PRIVATE KEY-----"""


import djcelery
djcelery.setup_loader()
BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_IMPORTS = ('CeleryTask.tasks')
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_SCHEDULER= 'djcelery.schedulers.DatabaseScheduler'


from celery.schedules import crontab
from celery.schedules import timedelta
CELERYBEAT_SCHEDULE = {
    u'测试任务1':{
        "task" : "CeleryTask.tasks.sendDing",
        "schedule":timedelta(seconds=1)
    }
}

ERROR_PATH = os.path.join(BASE_DIR,"error.log")

DING_URL="https://oapi.dingtalk.com/robot/send?access_token=5c198e400fe6217744436b9c040b3ddbea271c6195dd5c2b45fb86e5b4ae6f8f"



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION':["127.0.0.1:11211"]
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'
