# Generated by Django 2.1.8 on 2019-09-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_valid_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods_price',
            new_name='goods_pirce',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='goods_picture',
            new_name='goods_priture',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='payorder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
